### PR TITLE
camptocamp/systemd: Allow 3.x

### LINKED ISSUE #875: Not compatible with latest puppet-systemd
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.21.1
- Ruby: 2.5
- Distribution: CentOS8
- Module version: Latest puppet-rabbitmq commit

## How to reproduce (e.g Puppet code you use)
with latest puppet-systemd commit issue should be seen as the removed class is being used in puppet-rabbitmq https://github.com/voxpupuli/puppet-rabbitmq/blob/7f806ac6983ec8d087a2c9e86b4e1467198d6981/manifests/service.pp#L26-L28

## What are you seeing
Could not find resource 'Class[Systemd::Systemctl::Daemon_reload]' for relationship on 'Service[rabbitmq-server]' 

## What behaviour did you expect instead
It should be made compatible with latest puppet-systemd(no tag released yet). We test latest commits and hit the issue for now we have pinned puppet-systemd on our side https://review.rdoproject.org/r/#/c/32088/.

## Output log
https://logserver.rdoproject.org/ci.centos.org/weirdo-generic-packstack-scenario001/12896/weirdo-project/logs/latest/manifests/192.168.1.213_controller.pp.log.txt.gz

## Any additional information you'd like to impart
https://github.com/camptocamp/puppet-systemd/commit/97dd16fa32886b5b0f77a6f38a4953d4c1511c0e dropped support for puppet 4 and 5 as they are EOL, and removed Systemd::Systemctl::Daemon_reload with reasoning that it's not needed with puppet6.

### PR DESCRIPTION
**Pull request by bastelfreak**
also contains:
* https://github.com/voxpupuli/puppet-rabbitmq/pull/880
* https://github.com/voxpupuli/puppet-rabbitmq/pull/882

Closes #875

### CODE REVIEW

**Comment by wyardley** [comment]
@bastelfreak I don't think all these failures are still expected / ok, right?

**Comment by wyardley** [comment]
@bastelfreak can you rebase this one from #886

**Comment by bastelfreak** [comment]
@wyardley done

**Comment by wyardley** [comment]
@bastelfreak we still need the systemd metadata change here because #885 didnt add it

**Comment by bastelfreak** [comment]
@wyardley now it's fine

**Pull request merged**
