### PR TITLE
modulesync 2.7.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 2.7.0

### CODE REVIEW

**Comment by wyardley** [comment]
@bastelfreak didn't we drop Puppet4 in #761?

**Comment by dhoppe** [comment]
> @bastelfreak didn't we drop Puppet4 in #761?
Yes, this is just a custom message of ```msync```.

**Comment by wyardley** [comment]
@dhoppe @bastelfreak let me know if the PR title / labels look right now

**Comment by bastelfreak** [comment]
Those were automated PRs that matched most of the modules, I'm currently adjusting the few that need manual intervention.

**Pull request merged**
