### PR TITLE
Use data-in-modules instead of params.pp

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by dhoppe** [comment]
Do we really need to keep the ```server.pp```? It seems to be some kind of wrapper for backward compatibility and this will be a major release.

**Comment by wyardley** [comment]
I think it was already deprecated. Should be fine to pull it out.

**Comment by dhoppe** [comment]
@wyardley Yes, I wanted to make sure that the default values are fetched correctly.

**Comment by wyardley** [comment]
@dhoppe Yeah, forgot there isn't really a task to do that automagically yet... :/

**Comment by kobybr** [comment]
This should have been tagged as a breaking change.  Previous parameter references have been used in control repos.
 For example $rabbitmq::params::ssl_management_port is now $rabbitmq:::ssl_management_port.

**Comment by wyardley** [comment]
Not much that can be done about it at this point even if that were the case, but I think params was always supposed to be private 

And the class was marked as private well before this version was released

https://github.com/voxpupuli/puppet-rabbitmq/blob/9924ca115bb0aecaa0f8b4158d23d44fee3b8610/manifests/params.pp#L3

**Comment by kobybr** [comment]
Yes, I see that was added in 8.4.1 - however, we implemented this module prior to that.   As a volunteer effort I pointed this out not to complain, but to help for future releases.   Anyways, thanks for responding it is much appreciated.

**Pull request merged**
