### PR TITLE
Handle rabbitmq.config when cluster_nodes is empty

### PR DESCRIPTION
**Pull request by nosrio**
#### Pull Request (PR) description
Fix cluster config when `cluster_nodes` is empty

Followup to #978

### CODE REVIEW

**Comment by nosrio** [comment]
Hi @wyardley, could you pleae re run github action? 
I believe that the timeout error is not related to my change.

**Comment by wyardley** [comment]
Rerunning
Can you reference the original PR / commit this was related to (#978) in the commit message?

**Comment by wyardley** [comment]
Also, can you double-check that the email you're using for commits is tied to your GitHub username and / or amend the author on your commit?
Your profile doesn't show up in the UI next to the commit

image

**Review by wyardley — APPROVED** [review]
LGTM
If you are able to implement a unit test that would have caught this issue (could be a followup PR if you'd like to get this out fast), that would also be excellent.

**Comment by nosrio** [comment]
Done

**Comment by wyardley** [comment]
I will try to get this out soon, probably after I get someone to look at #991 and then once I can get approval on a release PR

**Pull request merged**
