### PR TITLE
Refactor manifests

### PR DESCRIPTION
**Pull request by dhoppe**
The following classes still have to be refactored:
- [ ] config.pp
- [ ] server.pp
- [ ] repo/apt.pp
- [ ] repo/rhel.pp

The classes ```apt.pp``` and ```rhel.pp``` depend on pr #797. 

I also need to know which Mirror we want to use as default and change the GPG key. I would like to use Bintray, because it provides packages for Erlang. 

Because of the many changes to the code we will have to release a major release anyway.

### CODE REVIEW

**Comment by wyardley** [comment]
#781 has some more info about the keys. I like the suggestion to just bake the files directly into the module; this is probably the most secure option.

**Comment by wyardley** [comment]
Also, I don’t have a preference on mirror, but packagecloud has their erlang packages too:
 https://packagecloud.io/rabbitmq/erlang

**Comment by dhoppe** [comment]
> Also, I don’t have a preference on mirror, but packagecloud has their erlang packages too:
> https://packagecloud.io/rabbitmq/erlang

Yes, but they only provide Erlang packages for RedHat/CentOS.

**Comment by dhoppe** [comment]
> #781 has some more info about the keys. I like the suggestion to just bake the files directly into the module; this is probably the most secure option.

Yes, but I do not know if we just need to provide the latest GPG key. My understanding was that they resigned all packages with the current GPG key.

**Comment by bastelfreak** [comment]
@dhoppe can you please rebase?

**Comment by wyardley** [comment]
@dhoppe do you want to work on this some more? I probably should cut a major release soon, and it would be nice to include these changes if you're able to update them.

**Comment by wyardley** [comment]
@dhoppe I'm going to close this one for now; feel free to reopen / revisit when you're ready to work on this again.

**Pull request closed without merging**
