### PR TITLE
Add in archive_options to pass settings to Archive used to download r…

### PR DESCRIPTION
**Pull request by paebersold**
…abbitmqadmin file

### CODE REVIEW

**Comment by paebersold** [comment]
try again will less typos :)

**Comment by wyardley** [comment]
Looks about right to me except for one remaining rubocop warning. Not sure if you're going to resubmit again, but just to give a bit more info on how best to squash commits, you can rebase with `git rebase -i HEAD~N` (with N being the total # of commits you want to squash / reorganize), edit 'pick' to 'f' for all lines except the initial commit, and then `git push -f`?

If you do your changes in a separate branch (in the future), it will also make it easier for you to keep your master branch clean / synced with Vox upstream, as well as making it easier to rebase. Hope this helps.

**Comment by paebersold** [comment]
thanks @wyardley - sorry for the mess.  My test env. is a mess so having to fight rubocop the hard way.

**Comment by wyardley** [comment]
Implemented in #681

**Pull request closed without merging**
