### PR TITLE
release 10.2.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by wyardley — COMMENTED** [review]
Did you run the strings update task?

**Comment by bastelfreak** [comment]
good catch. Seems to be broken :(

```
$ bundle exec rake reference
[warn]: Missing @param tag for parameter 'service_ensure' near manifests/service.pp:4.
[warn]: Missing @param tag for parameter 'service_manage' near manifests/service.pp:4.
[warn]: Missing @param tag for parameter 'service_name' near manifests/service.pp:4.
[warn]: Missing @param tag for parameter 'location' near manifests/repo/apt.pp:6.
[warn]: Missing @param tag for parameter 'repos' near manifests/repo/apt.pp:6.
[warn]: Missing @param tag for parameter 'include_src' near manifests/repo/apt.pp:6.
[warn]: Missing @param tag for parameter 'key' near manifests/repo/apt.pp:6.
[warn]: Missing @param tag for parameter 'key_source' near manifests/repo/apt.pp:6.
[warn]: Missing @param tag for parameter 'key_content' near manifests/repo/apt.pp:6.
[warn]: Missing @param tag for parameter 'architecture' near manifests/repo/apt.pp:6.
[warn]: Missing @param tag for parameter 'location' near manifests/repo/rhel.pp:4.
[warn]: Missing @param tag for parameter 'key_source' near manifests/repo/rhel.pp:4.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/rabbitmq_user.rb:23.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/rabbitmq_queue.rb:19.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/rabbitmq_vhost.rb:14.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/rabbitmq_plugin.rb:20.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/rabbitmq_policy.rb:17.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/rabbitmq_binding.rb:41.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/rabbitmq_exchange.rb:20.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/rabbitmq_parameter.rb:24.
[warn]: Missing a description for Puppet resource parameter 'path' at lib/puppet/type/rabbitmq_erlang_cookie.rb:14.
[warn]: Missing a description for Puppet resource parameter 'force' at lib/puppet/type/rabbitmq_erlang_cookie.rb:35.
[warn]: Missing a description for Puppet resource parameter 'rabbitmq_user' at lib/puppet/type/rabbitmq_erlang_cookie.rb:40.
[warn]: Missing a description for Puppet resource parameter 'rabbitmq_group' at lib/puppet/type/rabbitmq_erlang_cookie.rb:44.
[warn]: Missing a description for Puppet resource parameter 'rabbitmq_home' at lib/puppet/type/rabbitmq_erlang_cookie.rb:48.
[warn]: Missing a description for Puppet resource parameter 'service_name' at lib/puppet/type/rabbitmq_erlang_cookie.rb:52.
[warn]: Missing a description for Puppet resource property 'ensure' at lib/puppet/type/rabbitmq_user_permissions.rb:13.
[warn]: Missing a description for Puppet provider 'rabbitmqctl' (resource type 'rabbitmq_user') at lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb:2.
[warn]: Missing a description for Puppet provider 'rabbitmqctl' (resource type 'rabbitmq_vhost') at lib/puppet/provider/rabbitmq_vhost/rabbitmqctl.rb:2.
[warn]: Missing a description for Puppet provider 'ruby' (resource type 'rabbitmq_erlang_cookie') at lib/puppet/provider/rabbitmq_erlang_cookie/ruby.rb:3.
[warn]: Missing a description for Puppet provider 'rabbitmqctl' (resource type 'rabbitmq_policy') at lib/puppet/provider/rabbitmq_policy/rabbitmqctl.rb:5.
[warn]: Missing a description for Puppet provider 'rabbitmqadmin' (resource type 'rabbitmq_queue') at lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb:5.
[warn]: Missing a description for Puppet provider 'rabbitmqadmin' (resource type 'rabbitmq_binding') at lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb:6.
[warn]: Missing a description for Puppet provider 'rabbitmqctl' (resource type 'rabbitmq_parameter') at lib/puppet/provider/rabbitmq_parameter/rabbitmqctl.rb:5.
[warn]: Missing a description for Puppet provider 'rabbitmqadmin' (resource type 'rabbitmq_exchange') at lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb:3.
[warn]: Missing a description for Puppet provider 'rabbitmqplugins' (resource type 'rabbitmq_plugin') at lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb:4.
[warn]: Missing a description for Puppet provider 'rabbitmqctl' (resource type 'rabbitmq_user_permissions') at lib/puppet/provider/rabbitmq_user_permissions/rabbitmqctl.rb:2.
Files:                   29
Modules:                  0 (    0 undocumented)
Classes:                  1 (    1 undocumented)
Constants:                0 (    0 undocumented)
Attributes:               0 (    0 undocumented)
Methods:                  5 (    4 undocumented)
Puppet Classes:           8 (    0 undocumented)
Puppet Data Types:        0 (    0 undocumented)
Puppet Data Type Aliases:     0 (    0 undocumented)
Puppet Defined Types:     0 (    0 undocumented)
Puppet Types:            10 (    0 undocumented)
Puppet Providers:        10 (   10 undocumented)
Puppet Functions:         0 (    0 undocumented)
Puppet Tasks:             0 (    0 undocumented)
Puppet Plans:             0 (    0 undocumented)
 55.88% documented
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/base.rb:173:in `word_wrap'
(erb):119:in `block in render'
(erb):100:in `each'
(erb):100:in `render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/base.rb:181:in `render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/resource_type.rb:11:in `render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/resource_types.rb:22:in `block in render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/resource_types.rb:21:in `each'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown/resource_types.rb:21:in `render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown.rb:22:in `generate'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown.rb:38:in `block in render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown.rb:38:in `open'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/markdown.rb:38:in `render'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings.rb:81:in `render_markdown'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings.rb:62:in `generate'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/tasks/generate.rb:43:in `block (2 levels) in <top (required)>'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/puppet-strings-2.5.0/lib/puppet-strings/tasks/generate.rb:49:in `block (3 levels) in <top (required)>'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/Rakefile:24:in `block in <top (required)>'
/home/bastelfreak/modulesync_config/modules/voxpupuli/puppet-rabbitmq/.vendor/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/bastelfreak/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/home/bastelfreak/.gem/ruby/2.7.0/bin/bundle:23:in `load'
/home/bastelfreak/.gem/ruby/2.7.0/bin/bundle:23:in `<main>'
Tasks: TOP => strings:generate
(See full trace by running task with --trace)
```

**Comment by wyardley** [comment]
@bastelfreak huh. it worked for me on the last release. IIRC, I used `bundle exec rake strings:generate:reference` (based on https://voxpupuli.org/docs/releasing_version/) -- not sure if that's the same task

**Comment by wyardley** [comment]
maybe something with the new modulesync? I tried checkout out the PR to a local branch and running the task with my previous bundle and

```diff
diff --git a/REFERENCE.md b/REFERENCE.md
index 5399ff1..8e58745 100644
--- a/REFERENCE.md
+++ b/REFERENCE.md
@@ -435,9 +435,9 @@ Default value: `false`
 
 ##### `ldap_server`
 
-Data type: `String`
+Data type: `Variant[String[1],Array[String[1]]]`
 
-LDAP server to use for auth.
+LDAP server or servers to use for auth.
 
 Default value: 'ldap'
 ```

I can reproduce your error after a `bundle update`

**Review by llowder — APPROVED** [review]

**Pull request merged**
