### PR TITLE
Remove support for CentOS 6

### PR DESCRIPTION
**Pull request by towo**
#### Pull Request (PR) description

Support for CentOS 6 is removed from `metadata.json`. There was no stale code to refactor.

CentOS 6 support is making the CI a bad shade of red, and CentOS 6 is EOL, so it should be removed.

Additionally remove a leftover `.nodesets.yml`.

#### This Pull Request (PR) fixes the following issues

n/a

### CODE REVIEW

**Comment by wyardley** [comment]
Do you have a link to failed runs? IIRC, Vox hasn’t broadly dropped support though I know there was some discussion of it, and fairly recent PRs have been green IIRC

**Comment by towo** [comment]
@wyardley Sure, #869 has failed CentOS 6 runs where everything else is green. Problem is that the repositories aren't available anymore to pull packages from.

**Comment by wyardley** [comment]
@bastelfreak do we flag this as backwards-incompatible?

**Comment by bastelfreak** [comment]
yes. just backwards-incompatible. otherwise it might confuse the changelog generator.

**Pull request merged**
