### PR TITLE
Release 10.3.0

### PR DESCRIPTION
**Pull request by wyardley**
#### Pull Request (PR) description
Release 10.3.0:

* Add new parameter autoconvert for rabbitmq_parameter (@joec4i) (#865)
* Ensure :autoconvert is initialized before :value for rabbitmq_parameter (@joec4i) (#867)
* modulesync 3.1.0 (@bastelfreak) (#864)
* modulesync 4.0.0 (@bastelfreak) (#866)

### CODE REVIEW

**Comment by bastelfreak** [comment]
please also update the changelog

**Review by ekohl — COMMENTED** [review]
I'm not a fan of the `chore: ` prefix in commit messages.

**Comment by wyardley** [comment]
Oops, yeah, forgot the changelog with all the fuss getting the strings to update (still doesn’t work with latest puppet-strings)

**Comment by wyardley** [comment]
> I'm not a fan of the chore: prefix in commit messages

If Vox ever decides on a convention, I’ll be happy to follow it.

**Comment by ekohl** [comment]
> If Vox ever decides on a convention, I’ll be happy to follow it. For now, there’s no convention, so using the conventional commits / angular style I’m used to seems reasonable enough.

What I've seen the most is to write only `Release x.y.z`. IMHO that's a convention.

**Comment by wyardley** [comment]
> What I've seen the most is to write only Release x.y.z. IMHO that's a convention.

It doesn't matter too much to me, but what I meant was, an overall convention like https://www.conventionalcommits.org/en/v1.0.0-beta.2/ or any competing standard (whether it's Angular style or not) to get the meaning / commit type from _any_ commit (not just release commits). While it would be potentially hard to get people to update their commits, there are tools to enforce conventions in CI, and regardless of how you feel about it aesthetically, it really simplifies versioning, changelog generation, etc. much more so than the existing approach with labels.

So, Vox may have a de facto convention that applies to release PRs / commits only, but AFAICT but it's not mentioned in https://voxpupuli.org/docs/releasing_version/, and it's not an overarching convention in terns of how commit messages should be written more generally.

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
> It doesn't matter too much to me, but what I meant was, an overall convention like https://www.conventionalcommits.org/en/v1.0.0-beta.2/ or any competing standard (whether it's Angular style or not) to get the meaning / commit type from _any_ commit (not just release commits). While it would be potentially hard to get people to update their commits, there are tools to enforce conventions in CI, and regardless of how you feel about it aesthetically, it really simplifies versioning, changelog generation, etc. much more so than the existing approach with labels.

I strongly dislike that style. Every time I see it, it annoys me. I'd oppose adopting that for VP.

Today we already have a different method of generating the changelog and versioning. While they're not the best, they at least make it easy to adjust later on. If it's in git, that means it must be reviewed as part of the PR. That's easy to forget. It also increases the burden to contribute.

**Pull request merged**
