### PR TITLE
Add support for RHEL/CentOS 8

### LINKED ISSUE #816: Add support for RHEL/CentOS 8
The module is currently not supported on RHEL/CentOS 8. Please add support for those os versions.

### PR DESCRIPTION
**Pull request by dhoppe**
Fixes #816

### CODE REVIEW

**Comment by bastelfreak** [comment]
This depends on https://github.com/camptocamp/facterdb/pull/137 :(. We need to wait with the merge of this PR or we pin facterdb to the commit with CentOS 8 factsets.

**Comment by dhoppe** [comment]
@bastelfreak I know that camptocamp takes some time to merge pull requests, but pinning facterdb to the commit ID feels dirty, too.

**Comment by bastelfreak** [comment]
I think pinning it is totally fine as a workaround. We already did that in a few other modules as well. I also pinged Raphael again to kick of a facterdb release.

**Comment by ghoneycutt** [comment]
This seems to be failing because it is trying to download puppet for fedora 31 which does not exist. http://yum.puppetlabs.com/puppet5-release-fedora-30.noarch.rpm is the latest release.

**Comment by dhoppe** [comment]
@ghoneycutt This is not related to Fedora 31. The build jobs for CentOS 8 fail. 

By default the parameter ```repos_ensure``` is set to false, but the module ```garethr/erlang``` will enable the EPEL repository, which is used to install the package ```rabbitmq-server```. But the EPEL repository does not contain a ```rabbitmq-server``` package for CentOS 8. 

Does anybody know, why this module does not use the Packagecloud repository to install RabbitMQ?

**Comment by wyardley** [comment]
@dhoppe originally, the RMQ packages were the default. Quite a while back, when Puppet was still maintaining this module, I talked with the folks there and decided to rework it to default to using vendor packages vs packagecloud. I don’t remember all of the details, probably may be some more in the PR comments (#493).

At that time, I don’t think the OS vendor packages were so far out of date, and seemed like a sane default.

As far as the erlang dep, the erlang module isn’t really maintained now, so adjusting the strategy of which erlang version to get from where may also make some sense.

However, I haven’t had the time, need, or inclination to do the structural work involved in redoing the erlang installation, default package version, and integration tests.

As far as erlang dep goes, I think one challenge is making the module have somewhat sane defaults but also deal with cases where erlang is already present from something else the (module) user has done.

**Comment by nmaludy** [comment]
Restarting build job as https://github.com/camptocamp/facterdb/pull/137 was merged

**Comment by dhoppe** [comment]
Travis CI still fails, because stahnma/puppet-module-epel#61 has not been merged.

**Comment by wyardley** [comment]
@dhoppe let me know if you want any more input / background on this. I don't have the energy / need to make changes, but happy to review, and I do think it does make sense to do a major where we switch back to the default of using the RabbitMQ repos.

The thing (maybe mentioned in some other threads) that's also tricky is the different possible methods of satisfying the erlang deps, and the fact that, I think, the puppet erlang module isn't really maintained. So any updates would probably need to accommodate a couple different ways of satisfying the erlang deps.

**Comment by nmaludy** [comment]
I've been looking into this because a module i maintain `stackstorm/st2` depends on this module for RabbitMQ. I think the current piece being held up is that the current erlang module is no longer maintained and EPEL for EL8 doesn't contain the erlang dependencies we need.

I'll see if next week i can take a swing a making a new erlang module and donating it to Vox so we can maintain this as a community going forward.

Thoughts?

**Comment by nmaludy** [comment]
Sorry, i take that back, it looks like erlang installs correctly, but EPEL no longer includes `rabbitmq-server`. We may need to rely on the PackageCloud or Bintray repositories on EL8 to get rabbitmq-server: https://www.rabbitmq.com/install-rpm.html

**Comment by wyardley** [comment]
That would be great (new erlang module).

**Comment by wyardley** [comment]
@nmaludy it may work already if you set `repos_ensure` to `true`

**Comment by nmaludy** [comment]
@wyardley OK, i'll give that a shot on my local box. We may have to adjust the acceptance tests for el8 to set that as default, then probably set it up that way in `params.pp` and/or document it in the README.

**Comment by nmaludy** [comment]
@wyardley I was able to get this working on a local CentOS 8 Vagrant box with the following:
```
class { 'erlang': epel_enable => true, }
~> class { 'rabbitmq' : }
```

But, i also had to modify `hiera.yaml` to add a new data layer:
```yaml
  - name: 'Operating System Family Version'
    path: "family/%{facts.os.family}-%{facts.os.release.major}.yaml"
```

And then add the following hiera data file: `data/family/RedHat-8.yaml`
```yaml
---
rabbitmq::python_package: 'python3'
rabbitmq::repos_ensure: true
```

Going to create a PR now.

**Comment by nmaludy** [comment]
New PR is available here: #842

**Pull request closed without merging**
