### PR TITLE
puppetlabs/stdlib: Allow 9.x

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by maureen-lawless** [comment]
@bastelfreak any idea when this pull request will be released?

**Comment by bastelfreak** [comment]
@maureen-lawless someone needs to work on the failing tests. I currently do not have the capacity for this. Are you interested in taking a look?

**Comment by wyardley** [comment]
Rebased

**Comment by wyardley** [comment]
Seems like at least will for sure need #952

**Pull request closed without merging**
