### PR TITLE
Add auto cluster configuration support

### PR DESCRIPTION
**Pull request by vchepkov**
- added clustername fact and spec tests for it
- added rabbitmq_cluster type and provider with tests

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hey @vchepkov, thanks for picking this up. Can you take a look at the failing travis jobs?

**Comment by vchepkov** [comment]
I afraid tests are not my forte. I will see if I can copy&paste something, that's an extent of my expertise here :)

**Comment by KlavsKlavsen** [comment]
Really hoping this gets in.. would make cluster setup soo much easier :)

**Comment by KlavsKlavsen** [comment]
I just realized that if you give rabbitmq nodenames in FQDN format - it removes the domain part - and you cannot join - unless you give that name (ie. hostname part only). But in the acceptance test here - init_node is set from $facts['fqdn'] - which won't work..
This should probably strip domain name part of a node name - before trying to join atleast.

**Comment by Fabian1976** [comment]
I ran in to this issue also because i used FQDN as cluster_node names
```
rabbitmq::cluster_nodes:
  - 'local-o-rmq001.example.com'
  - 'local-o-rmq002.example.com'
  - 'local-o-rmq003.example.com'
```

But switching them to hostname only:
```
rabbitmq::cluster_nodes:
  - 'local-o-rmq001'
  - 'local-o-rmq002'
  - 'local-o-rmq003'
```
(and make sure they would resolve in DNS, made the cluster work.

**Pull request closed without merging**
