### PR TITLE
Enable usage of custom list of plugins when using static config file

### PR DESCRIPTION
**Pull request by enothen**
This PR enables usage of a custom list of plugins when using a plugins config file, as reported on #916

### CODE REVIEW

**Comment by enothen** [comment]
Hello reviewers,
Not sure how to handle the failed validation, as it was already in master before this PR:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ git log --oneline |head -5
138a977 [blacksmith] Bump version to 12.0.3-rc0
7f384ce Merge pull request #914 from wyardley/wyardley/release_12_0_2
79949c2 Release 12.0.2
3f811e5 Merge pull request #912 from kvisle/bugfix/plugin_resource_broken_310
3436f22 Make rabbitmq_plugin resource functional on RabbitMQ 3.10.x
$ bundle exec rake lint
manifests/config.pp:131:manifest_whitespace_opening_brace_before:ERROR:there should be a single space before an opening brace
```
Since the problem is unrelated to this PR, should I fix it here or open a separate issue?

**Comment by wyardley** [comment]
Hi. Yes, can you make a separate PR with just that fix? It passed on the last run I can find.

**Comment by enothen** [comment]
> Hi. Yes, can you make a separate PR with just that fix? It passed on the last run I can find.

Done, https://github.com/voxpupuli/puppet-rabbitmq/pull/918

**Review by leifmadsen — APPROVED** [review]

**Comment by enothen** [comment]
Can someone please rerun the tests? They should be fone now that #918 is merged.

**Comment by kenyon** [comment]
Rebasing on current master will rerun the tests.

**Comment by enothen** [comment]
> Rebasing on current master will rerun the tests.

Thanks. Rebased, fixed a syntax warning in the test case, squashed and pushed again. Now I'm getting a failed job just on Archlinux, but seems to be unrelated to the changes. I'm not so sure what to make out of the logs yet.

**Comment by wyardley** [comment]
Yeah, arch failures have been there a while and are unrelated.

**Pull request merged**
