### PR TITLE
Add support to uninstall rabbitmq plugins.

### PR DESCRIPTION
**Pull request by acowan**
This is an update of pull request #388 from 14 Sep 2015.  There have been quite a number of changes to puppetlabs-rabbitmq in the interim, so I rewrote the patch.

### CODE REVIEW

**Comment by acowan** [comment]
Looks like a broken test run -- unlikely that I broke every test case.

**Comment by wyardley** [comment]
@acowan this may get a little more traction now that the module is under Voxpupuli, however, can you rebase against master (and squash commits if you can)? That should trigger a new run of the acceptance tests too.

**Comment by wyardley** [comment]
This can also probably be done more cleanly now that we have data types and have true booleans for most (all?) of these options.

**Comment by wyardley** [comment]
I'm going to close this for now, since there's been no action for a while.

**Pull request closed without merging**
