### PR TITLE
puppetlabs/stdlib: Allow 9.x

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by wyardley — APPROVED** [review]

**Review by wyardley — COMMENTED** [review]
Note: from my experiments yesterday, I think there might be some previously deprecated methods that are fully dropped? So we might want to do this as a breaking change and update any removed or deprecated methods at the same time?

**Comment by bastelfreak** [comment]
that's why I want to get the puppet 8 PR in. CI will fail on puppet 8 when we use deprecated functions.

**Comment by wyardley** [comment]
Seems like this one passes now, though? With or without Puppet 8, does it make sense to drop support for older stdlib as a breaking change (with removal of those methods)? I'm good either way - if you think this one is good, let's :shipit:

**Comment by wyardley** [comment]
I noticed that the GH UI isn't setup to suggest / warn when the base needs to be updated if there are no conflicts - would it make sense to add that in the branch protection settings if someone's got that power?

**Review by TheMeier — APPROVED** [review]

**Pull request merged**
