### PR TITLE
Fix regex double escaping of rabbitmqctl list_policies

### PR DESCRIPTION
**Pull request by sspreitzer**

### CODE REVIEW

**Comment by devfaz** [comment]
+1

**Comment by DrOwl** [comment]
I have tested this patch and it fixes the problem for us we no longer get an update on each run:

before patch we get the below every run
/Stage[main]/manage_rabbitmq::Federation/Rabbitmq_policy[eu-federation@vhost]/pattern: pattern changed '^eu\\.' to '^eu\.'

**Comment by eputnam** [comment]
@sspreitzer could you add some unit tests for this?

**Comment by DrOwl** [comment]
Ok well i have no idea how add more to a pull request but here is some tests
[spec_test.patch.txt](https://github.com/puppetlabs/puppetlabs-rabbitmq/files/1128617/spec_test.patch.txt)

Theses have not been tested as "you guys and your crazzy Beaker"

**Comment by wyardley** [comment]
If folks don't mind, I added @DrOwl's test (with attribution to @sspreitzer for the whole commit, couldn't figure out how to break it up) and resubmitted as #561

**Pull request closed without merging**
