### PR TITLE
rabbitmq_policy should allow array in values, too

### PR DESCRIPTION
**Pull request by devfaz**
... because ha-mode = nodes needs array of used nodes

### CODE REVIEW

**Comment by devfaz** [comment]
... is there anybody out there?

**Comment by eserte** [comment]
I created a ticket for this issue: https://tickets.puppetlabs.com/browse/MODULES-4555

**Comment by eserte** [comment]
See also also the alternative PR (this one with test additions): https://github.com/puppetlabs/puppetlabs-rabbitmq/pull/537

**Comment by wyardley** [comment]
Looks like this can be closed by #537

**Pull request closed without merging**
